### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by viscerae** [JoseSoares01/Site_Zafirah#1]
Page formatting issues

**Comment by JoseSoares01** [comment]
We are already working on a possible bootstrap to improve formatting as well as direct font size settings on the page. Thanks for the collaboration.

**Comment by JoseSoares01** [comment]
We are already working on a possible bootstrap to improve formatting as well as direct font size settings on the page. Thanks for the collaboration.

**Comment by viscerae** [comment]
Fixed
